# restaurantlisting/src/main/resources/application-docker.yml

spring:
  application:
    name: RESTAURANT-SERVICE

server:
  port: 9091

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8762/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    hostname: restaurant-service
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always